### ISSUE TITLE
Not compatible with NGINX 1.23.0

### ISSUE THREAD

**Issue by dvershinin** [limithit/ngx_cookie_limit_req_module#5]
```
ngx_cookie_limit_req_module-1.1/ngx_http_cookie_limit_req_module.c: In function 'ngx_http_limit_req_handler':
ngx_cookie_limit_req_module-1.1/ngx_http_cookie_limit_req_module.c:210:33: error: 'ngx_http_headers_in_t' has no member named 'cookies'; did you mean 'cookie'?
  210 |         cookies = r->headers_in.cookies.elts;
      |                                 ^~~~~~~
      |                                 cookie
```

**Comment by limithit** [comment]
Bug fixed

**Comment by dvershinin** [comment]
Wouldn't that change break prior versions because now for those versions the code that will run is `cookies = r->headers_in.cookies.elts;` then ... `cookies->value.len` ? Maybe it had to be something like `cookies = r->headers_in.cookies.elts[0];`

**Comment by limithit** [comment]
No, it won't.  
![image](https://user-images.githubusercontent.com/7675726/175265624-7519e00f-5194-4b47-a033-7361ae914653.png)
