### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by sdfksdkf123** [limithit/ngx_cookie_limit_req_module#6]
this my script
```
#!/bin/bash
NGINX_VERSION=1.25.0

cd /tmp/
wget -c http://download.redis.io/releases/redis-4.0.8.tar.gz
tar -xvf redis-4.0.8.tar.gz
cd /tmp/redis-4.0.8/deps/hiredis
make 
make install 
echo /usr/local/lib >> /etc/ld.so.conf
ldconfig
cd /tmp/
wget https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz
tar -xzvf nginx-$NGINX_VERSION.tar.gz
git clone https://github.com/limithit/ngx_dynamic_limit_req_module.git
git clone https://github.com/limithit/ngx_cookie_limit_req_module.git
cd /tmp/nginx-$NGINX_VERSION/
./configure --with-compat --add-dynamic-module=../ngx_dynamic_limit_req_module --add-dynamic-module=../ngx_cookie_limit_req_module
make modules
service nginx stop
cp /tmp/nginx-$NGINX_VERSION/objs/ngx_http_dynamic_limit_req_module.so /usr/local/nginx/modules/
cp /tmp/nginx-$NGINX_VERSION/objs/ngx_cookie_limit_req_module.so /usr/local/nginx/modules/
service nginx restart
service nginx status
```

dynamic limit req work
cookie limit req crash on any request (if i load module only)
![image](https://github.com/limithit/ngx_cookie_limit_req_module/assets/131250349/8640bd46-adef-46c9-bd9e-567d5e5735be)

**Comment by sdfksdkf123** [comment]
can`t debug with this
```
sudo gdb /usr/sbin/nginx
(gdb) set args -c /etc/nginx/nginx.conf -p /var/log/nginx -g 'error_log /var/log/nginx/error.log;'
(gdb) run
```

**Comment by limithit** [comment]
![image](https://github.com/limithit/ngx_cookie_limit_req_module/assets/7675726/a4f2aed3-4bd5-4a34-9a49-256bce9e0a87)

![image](https://github.com/limithit/ngx_cookie_limit_req_module/assets/7675726/8bbf5e6e-3c61-42cb-9dfe-b437f466b06a)

I recompiled nginx1.25, both statically compiled and dynamically loaded, without reproducing the problem, you need to provide more compilation parameters and configuration.

**Comment by sdfksdkf123** [comment]
`I found the problem, if these lines are missing nginx crashes (only module loading)
cookie_limit_req_zone $http_cookie zone=two:10m rate=30r/s redis=127.0.0.1 block_second=300 cookie_max=5;
cookie_limit_req zone=two burst=30 nodelay;
cookie_limit_req_status 403;`

**Comment by sdfksdkf123** [comment]
fixed
